package news;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
//import com.vnetpublishing.java.suapp.ISuperUserApplication;
import com.notification.NotificationFactory;
import com.notification.NotificationFactory.Location;
import com.notification.NotificationManager;
import com.notification.manager.SimpleManager;
import com.notification.types.IconNotification;
import com.theme.ThemePackagePresets;
import com.utils.IconUtils;
import com.utils.Time;
import java.net.*;
import java.io.*;
import javax.swing.JOptionPane;
import java.awt.*;
import java.awt.Robot;
import java.awt.event.InputEvent;
import java.awt.event.KeyEvent;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.io.DataInputStream;
import java.io.FileInputStream;
import java.io.IOException;
import java.security.KeyManagementException;
import java.security.NoSuchAlgorithmException;
import java.security.cert.X509Certificate;
import java.util.Scanner;
import javax.net.ssl.HostnameVerifier;
import javax.net.ssl.HttpsURLConnection;
import javax.net.ssl.SSLContext;
import javax.net.ssl.SSLSession;
import javax.net.ssl.TrustManager;
import javax.net.ssl.X509TrustManager;
import javax.swing.UIManager;
import java.util.Timer;
import java.util.TimerTask;

 /*
 * @author Sanatt Abrol
 */
public class Form_Main extends javax.swing.JFrame {

    /**
     * Creates new form Form_Main
     */
  private static final String POST_CONTENT_TYPE = "application/x-www-form-urlencoded";
	    //private static final String LOGIN_USER_NAME_PARAMETER_NAME = "username";
	    //private static final String LOGIN_PASSWORD_PARAMETER_NAME = "password";
 
	    //private static final String LOGIN_USER_NAME = "be1048915";
	    //private static final String LOGIN_PASSWORD = "bitch";
            private static int COUNTER = 0;
            private static int COUNTER_0 = 0;
	    private static final String TARGET_URL = "https://172.16.1.1:8090/login.xml";
            private static final String TARGET_URL_0 = "https://172.16.1.1:8090/logout.xml";
//            main();
            static Timer timer = new Timer();
    static int seconds = 0;
      
    public Form_Main() {
        initComponents();
        //System.out.println(.2*.35);
        this.setLocationRelativeTo(null);
//        getContentPane().setBackground(new Color(21,21,21) );
        stop.setEnabled(false);
        jTextArea1.append("LOG STARTED");
        jTextArea1.append('\n'+"------------------------------------------------------------------"+'\n');
    try{
        ReadDAT();
        Thread.sleep(50);
        ReadDAT1();
        
        
    }
    catch(IOException e){} catch (InterruptedException ex) {
            Logger.getLogger(Form_Main.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSuccessFrame = new javax.swing.JFrame();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jFailureFrame = new javax.swing.JFrame();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jUsr = new javax.swing.JTextField();
        create = new javax.swing.JButton();
        stop = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jUsr1 = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jPsw1 = new javax.swing.JPasswordField();
        jPsw = new javax.swing.JPasswordField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jCheckBox5 = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();

        jSuccessFrame.setAlwaysOnTop(true);
        jSuccessFrame.setBackground(new java.awt.Color(0, 0, 204));
        jSuccessFrame.setMinimumSize(new java.awt.Dimension(310, 123));
        jSuccessFrame.setUndecorated(true);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("jLabel9");

        jLabel10.setForeground(new java.awt.Color(0, 51, 204));
        jLabel10.setText("has succesfully logged in!!");

        jLabel8.setForeground(new java.awt.Color(0, 51, 204));
        jLabel8.setText("Login Success. User");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 51, 204));
        jLabel11.setText(":)");

        jButton2.setText("X");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jSuccessFrameLayout = new javax.swing.GroupLayout(jSuccessFrame.getContentPane());
        jSuccessFrame.getContentPane().setLayout(jSuccessFrameLayout);
        jSuccessFrameLayout.setHorizontalGroup(
            jSuccessFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jSuccessFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jSuccessFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11)
                    .addGroup(jSuccessFrameLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addContainerGap(26, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jSuccessFrameLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addContainerGap())
        );
        jSuccessFrameLayout.setVerticalGroup(
            jSuccessFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jSuccessFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jSuccessFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jFailureFrame.setBackground(new java.awt.Color(0, 0, 102));
        jFailureFrame.setForeground(new java.awt.Color(0, 0, 153));
        jFailureFrame.setUndecorated(true);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 255));
        jLabel12.setText(":(");

        jLabel13.setForeground(new java.awt.Color(0, 0, 255));
        jLabel13.setText("Action Success. User");

        jLabel14.setForeground(new java.awt.Color(0, 0, 255));
        jLabel14.setText("is logged out");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setText("jLabel9");

        jButton4.setText("X");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jFailureFrameLayout = new javax.swing.GroupLayout(jFailureFrame.getContentPane());
        jFailureFrame.getContentPane().setLayout(jFailureFrameLayout);
        jFailureFrameLayout.setHorizontalGroup(
            jFailureFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFailureFrameLayout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(jLabel12)
                .addGap(150, 150, 150))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFailureFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addGap(17, 17, 17)
                .addComponent(jButton4)
                .addContainerGap())
        );
        jFailureFrameLayout.setVerticalGroup(
            jFailureFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFailureFrameLayout.createSequentialGroup()
                .addGroup(jFailureFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jFailureFrameLayout.createSequentialGroup()
                        .addContainerGap(25, Short.MAX_VALUE)
                        .addGroup(jFailureFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jLabel15)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jFailureFrameLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jLabel12)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Crap-WH");
        setBackground(new java.awt.Color(21, 21, 21));
        setForeground(new java.awt.Color(21, 21, 21));
        setResizable(false);

        create.setText("Start Wifi");
        create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createActionPerformed(evt);
            }
        });

        stop.setText("Stop Wifi");
        stop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopActionPerformed(evt);
            }
        });

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setWrapStyleWord(true);
        jScrollPane1.setViewportView(jTextArea1);

        jButton1.setText("Authenticate");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jCheckBox1.setText("Show Password");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jCheckBox2.setText("Save for next time");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });

        jCheckBox3.setText("Save for next time");
        jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3ActionPerformed(evt);
            }
        });

        jCheckBox4.setText("Show Password");
        jCheckBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox4ActionPerformed(evt);
            }
        });

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/1447781090_ic_wifi_lock_48px.png"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cyberoam.png"))); // NOI18N

        jLabel1.setText("SSID");

        jLabel4.setText("Password");

        jLabel5.setText("Username");

        jLabel6.setText("Password");

        jLabel18.setText("Having \"Limited Access\" ? check out the fix in the pdf file given along");

        jCheckBox5.setText("Authenticate on Application Startup");
        jCheckBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox5ActionPerformed(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/news/information.png"))); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });

        jLabel16.setText("Click on the blue icon to view application details");

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/news/information.png"))); // NOI18N
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel17MouseClicked(evt);
            }
        });

        jLabel19.setText("See hotspot info");
        jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel19MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jUsr)
                                .addComponent(jPsw, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(create)
                            .addComponent(stop))
                        .addGap(49, 49, 49))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1)
                            .addComponent(jLabel18)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckBox1)
                                    .addComponent(jCheckBox3)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(49, 49, 49)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel17)
                                            .addComponent(jLabel2))))
                                .addGap(2, 2, 2)
                                .addComponent(jLabel19)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPsw1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox2)
                    .addComponent(jCheckBox4)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel3))
                    .addComponent(jLabel5)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jUsr1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jButton1))
                    .addComponent(jCheckBox5, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(44, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel16)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jUsr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel4)
                                        .addGap(4, 4, 4)
                                        .addComponent(jPsw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(create)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(43, 43, 43)
                                            .addComponent(stop))))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jCheckBox1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jCheckBox3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel19)
                                            .addComponent(jLabel17))
                                        .addGap(34, 34, 34))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(jLabel18))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jUsr1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6))
                            .addComponent(jButton1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPsw1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCheckBox4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox5)
                        .addGap(0, 13, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel16)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private String readResponse(HttpURLConnection urlConnection) throws IOException
    {
 
        BufferedReader bufferedReader = null;
        try
        {
            // Prepare a reader to read the response from the URLConnection
            // throws IOException
            bufferedReader = new BufferedReader(new InputStreamReader(urlConnection.getInputStream()));
            String responeLine;
 
            // Good Practice: Use StringBuilder in this case
            StringBuilder response = new StringBuilder();
 
            // Read until there is nothing left in the stream
            // throws IOException
            while ((responeLine = bufferedReader.readLine()) != null)
            {
                response.append(responeLine);
            }
           
 
            return response.toString();
            //bufferedReader.close();
        }
        catch(IOException ioException)
        {
            System.out.println("Problems while reading the response");
            ioException.printStackTrace();
 
            // throw the exception so that the caller is aware that
            // there was some problems
            throw ioException;
 
        }
        finally
        {
            // Good practice: clean up the connections and streams
            // to free up any resources if possible
            if (bufferedReader != null)
            {
                try
                {
                    // throws IOException
                    bufferedReader.close();
                }
                catch(Throwable ignore)
                {
                    // Cannot do much with exceptions doing clean up
                    // Ignoring all exceptions
                }
            }
 
        }
    }
    public static void NoCheck() throws NoSuchAlgorithmException, KeyManagementException
        {
            TrustManager[] trustAllCerts = new TrustManager[] {
       new X509TrustManager() {
          public java.security.cert.X509Certificate[] getAcceptedIssuers() {
            return null;
          }

          public void checkClientTrusted(X509Certificate[] certs, String authType) {  }

          public void checkServerTrusted(X509Certificate[] certs, String authType) {  }

       }
    };

    SSLContext sc = SSLContext.getInstance("SSL");
    sc.init(null, trustAllCerts, new java.security.SecureRandom());
    HttpsURLConnection.setDefaultSSLSocketFactory(sc.getSocketFactory());

    // Create all-trusting host name verifier
    HostnameVerifier allHostsValid = new HostnameVerifier() {
        public boolean verify(String hostname, SSLSession session) {
          return true;
        }
    };
    // Install the all-trusting host verifier
    HttpsURLConnection.setDefaultHostnameVerifier(allHostsValid);
    /*
     * end of the fix
     */
    
        
        }
    
    public void Cyberoam(int x,String u, String p) throws NoSuchAlgorithmException, KeyManagementException, InterruptedException
    {
         NoCheck();
        httpPostLogin(x,u,p);
    
    }
    
    public void httpPostLogin (int x,String u,String p) throws InterruptedException
    {
        try
        {
            // Prepare the content to be written
            // throws UnsupportedEncodingException
            String urlEncodedContent = preparePostContent(x,u, p);
 
            System.out.println(urlEncodedContent);
            
            HttpURLConnection urlConnection = doHttpPost(x,TARGET_URL, urlEncodedContent);
                System.out.println('\n' + " Step 1");
            String response = readResponse(urlConnection);
            char a = response.charAt(119);
            if(x==0)
                a=response.charAt(120);
            //JOptionPane.showMessageDialog(null,a);
            System.out.println("Successfully made the HTPP POST.");
            System.out.println("Recevied response is: '/n" + response + "'");
            //String build = "<?xml version='1.0' ?><requestresponse><status><![CDATA[LIVE]]></status><message><![CDATA[You have successfully logged in]]></message><logoutmessage><![CDATA[You have successfully logged off]]></logoutmessage><state><![CDATA[]]></state></requestresponse>";
            //String build0 = "<?xml version='1.0' ?><requestresponse><status><![CDATA[LIVE]]></status><message><![CDATA[You have successfully logged off]]></message><logoutmessage><![CDATA[You have successfully logged off]]></logoutmessage><state><![CDATA[]]></state></requestresponse>";
            //char a = response.charAt(119);
            
            if(a=='i')
                PostSuccess();
            else if(a=='o')
                PostFail();
            else if(response.contains("The system could not log you on. Make sure your password is correct"))
               JOptionPane.showMessageDialog(null,"The system could not log you on. Make sure your password is correct"); 
            else if(response.contains("You have reached Maximum Login Limit."))
                JOptionPane.showMessageDialog(null, "You have reached Maximum Login Limit");
            else 
                JOptionPane.showMessageDialog(null,response);
             
        }
        catch(IOException ioException)
        {
            System.out.println("Problems encounterd.");
        }
    }
 
    private String preparePostContent(int x,String loginUserName, String loginPassword) throws UnsupportedEncodingException
    {
        // Encode the user name and password to UTF-8 encoding standard
        // throws UnsupportedEncodingException
        String encodedLoginUserName = URLEncoder.encode(loginUserName, "UTF-8");
        String encodedLoginPassword = URLEncoder.encode(loginPassword, "UTF-8");
        int mode;
        if(x==1)
            mode=191;
        else
            mode=193;
       /* String content = "login=" + LOGIN_ACTION_NAME +" &" + LOGIN_USER_NAME_PARAMETER_NAME +"="
        + encodedLoginUserName + "&" + LOGIN_PASSWORD_PARAMETER_NAME + "=" + encodedLoginPassword;*/
       // int a = System.class.
        long a = System.currentTimeMillis();
        String content = "mode="+mode+"&username="+encodedLoginUserName+"&password="+encodedLoginPassword+"&a="+a+"&producttype=0";
 
        return content;
    
    }
    public HttpURLConnection doHttpPost(int x,String targetUrl, String content) throws IOException
    {
        HttpURLConnection urlConnection = null;
        DataOutputStream dataOutputStream = null;
        try
        {
            // Open a connection to the target URL
            // throws IOException
            if(x==0)
                targetUrl=TARGET_URL_0;
            urlConnection = (HttpURLConnection)(new URL(targetUrl).openConnection());
 
            // Specifying that we intend to use this connection for input
            urlConnection.setDoInput(true);
           // urlConnection = (HttpURLConnection) configureConnection(urlConnection);
            // Specifying that we intend to use this connection for output
            urlConnection.setDoOutput(true);
 
            // Specifying the content type of our post
            urlConnection.setRequestProperty("Content-Type", POST_CONTENT_TYPE);
            urlConnection.setRequestProperty("User-Agent", "Mozilla/5.0 (Windows; U; Windows NT 6.1; en-GB; rv:1.9.2.8) Gecko/20100722 Firefox/3.6.8");
 
            HttpURLConnection.setFollowRedirects(true);
            // Specifying the method of HTTP request which is POST
            // throws ProtocolException
            urlConnection.setRequestMethod("POST");
//           SSLUtilities.trustAllHostnames();
 //           SSLUtilities.trustAllHttpsCertificates();
        //    disableSSLCertificateChecking();
            // Prepare an output stream for writing data to the HTTP connection
            // throws IOException
            dataOutputStream = new DataOutputStream(urlConnection.getOutputStream());
 
            // throws IOException
            dataOutputStream.writeBytes(content);
            dataOutputStream.flush();
            dataOutputStream.close();
                System.out.println('\n' + " Step 2");
 
            return urlConnection;
        }
        catch(IOException ioException)
        {
            System.out.println("I/O problems while trying to do a HTTP post.");
            ioException.printStackTrace();
 
            // Good practice: clean up the connections and streams
            // to free up any resources if possible
            if (dataOutputStream != null)
            {
                try
                {
                    dataOutputStream.close();
                }
                catch(Throwable ignore)
                {
                    // Cannot do anything about problems while
                    // trying to clean up. Just ignore
                }
            }
            if (urlConnection != null)
            {
                urlConnection.disconnect();
            }
 
            // throw the exception so that the caller is aware that
            // there was some problems
            throw ioException;
        }
    }
    private void createActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createActionPerformed
        // TODO add your handling code here:
        String usr=jUsr.getText();
        
        String psw=jPsw.getText();
        stop.setEnabled(true);
        create.setEnabled(false);
        CreateWifi(usr,psw);
        WifiStart();
       // java.awt.Desktop.getDesktop().
      
    }//GEN-LAST:event_createActionPerformed

    private void stopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopActionPerformed
create.setEnabled(true);
WifiStop();
stop.setEnabled(false);
// TODO add your handling code here:
    }//GEN-LAST:event_stopActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
//        if(jCheckBox5.isSelected()==false)
              // Authenticate(3000);
  //      else
             //  Authenticate(10000);
    //    Ping();
        try{
    int x=0;
    x=COUNTER-COUNTER_0;
    if(x==0)
        x=1;
    else if(x==1)
        x=0;
    Cyberoam(x,jUsr1.getText(),jPsw1.getText());
        
}
catch(Exception e)
{}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jCheckBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox4ActionPerformed
    // TODO add your handling code here:
if(jCheckBox4.isSelected()==true)
{
    JOptionPane.showMessageDialog(null,"pass is "+jPsw1.getText());
    jCheckBox4.setSelected(false);
}
    }//GEN-LAST:event_jCheckBox4ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
if(jCheckBox1.isSelected()==true)
{
    JOptionPane.showMessageDialog(null,"pass is "+jPsw.getText());
    jCheckBox1.setSelected(false);
}        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3ActionPerformed
try{
WriteDAT();
}
catch(Exception e){}        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox3ActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
try{
WriteDAT1();
}
catch(Exception e){}        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
jSuccessFrame.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
jFailureFrame.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jCheckBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox5ActionPerformed

try{
    
    WriteDAT1();

}

catch(Exception e)
{}// TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox5ActionPerformed

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
JOptionPane.showMessageDialog(null,"Crap-WH made by Sanatt Abrol BE/10489/15 using NetBeasn IDE 8.0");        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel17MouseClicked

    private void jLabel19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseClicked
try{
  Process p=Runtime.getRuntime().exec("cmd /c netsh wlan show hostednetwork"); 
             
          BufferedReader reader=new BufferedReader(new InputStreamReader(p.getInputStream()));
          String s,a="";  
          while((s=reader.readLine())!=null)
          {
              a+=s+'\n';
          }
          JOptionPane.showMessageDialog(null, a);
          
}
catch(HeadlessException | IOException e){
    
    }// TODO add your handling code here:
    }//GEN-LAST:event_jLabel19MouseClicked
    private void PostSuccess()
    {
    
        COUNTER++;
jButton1.setText("De-Authenticate");

    NotificationFactory factory = new NotificationFactory(ThemePackagePresets.cleanDark());
    NotificationManager man = new SimpleManager(Location.SOUTHEAST);
    IconNotification note = factory.buildIconNotification("Logged In", "User "+jUsr1.getText()+" has logged in", 
IconUtils.createIcon("/news/exclamation.png", 40, 40));
    note.setCloseOnClick(true);
    man.addNotification(note, Time.seconds(4));
    
    }
                //Form_Main.CENTER_ALIGNMENT;
                
             //   new Form_Main().setVisible(true);
                
               // Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
//Form_Main.class.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
             
                //stop.setEnabled(false);
                
    private void PostFail() throws InterruptedException
    {
        
//try{Thread.sleep(4000);jFailureFrame.setVisible(false);}catch(Exception e){}
    NotificationFactory factory = new NotificationFactory(ThemePackagePresets.cleanDark());
    NotificationManager man = new SimpleManager(Location.SOUTHEAST);
    IconNotification note = factory.buildIconNotification("Logged Out", "User "+jUsr1.getText()+" has logged out", 
IconUtils.createIcon("/news/exclamation.png", 40, 40));
    note.setCloseOnClick(true);
    man.addNotification(note, Time.seconds(4));
COUNTER_0++;
jButton1.setText("Authenticate");    
    }
    
    //@SuppressWarnings("empty-statement")
   
    public void ReadDAT() throws FileNotFoundException, IOException
        {
         
       File f = new File("dbs.dat");
       FileReader fw = new FileReader(f);    
       BufferedReader br = new BufferedReader(fw);
       Scanner sc = new Scanner(br);
       int i=0;
while(sc.hasNextLine() && i<3){

        if(i==0)
            jUsr.setText(sc.nextLine());
        else if(i==1)
            jPsw.setText(sc.nextLine());
        else if(i==2)
        {
            int x = Integer.parseInt(sc.nextLine());
            if(x==1)
                   jCheckBox3.setSelected(true);
        }
        
        i++;
}
    }
    public void ReadDAT1() throws FileNotFoundException, IOException
    {
       File f = new File("dbs1.dat");
       FileReader fw = new FileReader(f);    
       BufferedReader br = new BufferedReader(fw);
       Scanner sc = new Scanner(br);
       int i=0;
while(sc.hasNextLine() && i<4){

        if(i==0)
            jUsr1.setText(sc.nextLine());
        else if(i==1)
            jPsw1.setText(sc.nextLine());
        else if(i==2)
        {   
            int x = Integer.parseInt(sc.nextLine());
            if(x==1)
                   jCheckBox2.setSelected(true);
        }
        else if(i==3)
        {
            int x = Integer.parseInt(sc.nextLine());
            if(x==1)
            {
                jCheckBox5.setSelected(true);
                jButton1.doClick();
            }
        }
        i++;
}
      }
    
   public void WriteDAT() throws IOException
   {
       File f = new File("dbs.dat");
       FileWriter fw = new FileWriter(f);    
       BufferedWriter bw = new BufferedWriter(fw);
       bw.write(jUsr.getText()+"\n"+jPsw.getText()+"\n"+"1");
       bw.flush();
       bw.close();
   }
   
   public void WriteDAT1() throws IOException
   {
       File f = new File("dbs1.dat");
       FileWriter fw = new FileWriter(f);    
       BufferedWriter bw = new BufferedWriter(fw);
       if(jCheckBox5.isSelected())
           bw.write(jUsr1.getText()+"\n"+jPsw1.getText()+"\n"+"1"+"\n"+"1");
       else
           bw.write(jUsr1.getText()+"\n"+jPsw1.getText()+"\n"+"1");
       bw.flush();
       bw.close();
   }
   
    public void WifiStop(){
            try 
{ 
Process p=Runtime.getRuntime().exec("cmd /c netsh wlan stop hostednetwork"); 
p.waitFor(); 
BufferedReader reader=new BufferedReader(new InputStreamReader(p.getInputStream())); 
String line=reader.readLine(); 
while(line!=null) 
{ 
System.out.println(line);

jTextArea1.append('\n'+line);
line=reader.readLine(); 
} 

} 
catch(IOException e1) {
    stop.setEnabled(true);
JOptionPane.showMessageDialog(null,"Sorry! Can not configure this interface");
} 
catch(InterruptedException e2) {
    stop.setEnabled(true);
JOptionPane.showMessageDialog(null,"Sorry! Can not configure this interface");
}
    }
    public void CreateWifi(String usr,String psw){
           try 
{ 
Process p=Runtime.getRuntime().exec("cmd /c netsh wlan set hostednetwork mode=allow ssid="+usr+" key="+psw); 
p.waitFor(); 
BufferedReader reader=new BufferedReader(new InputStreamReader(p.getInputStream())); 
String line=reader.readLine();

jTextArea1.append('\n'+line);
while(line!=null) 
{
    if(line.equalsIgnoreCase("The hosted network couldn't be started."))
        {
                  JOptionPane.showMessageDialog(null,"Sorry! Can not configure this interface. WiFi device is switched off. Check log for further clarification.");
                  create.setEnabled(true);
        
        } 
System.out.println(line);
jTextArea1.append(line);
line=reader.readLine(); 
} 

} 
catch(IOException e1) {
JOptionPane.showMessageDialog(null,"Sorry! Can not configure this interface");
stop.setEnabled(false);
} 
catch(InterruptedException e2) {
stop.setEnabled(false);    
JOptionPane.showMessageDialog(null,"Sorry! Can not configure this interface");} 

       }
 public void WifiStart(){
            try 
{ 
Process p=Runtime.getRuntime().exec("cmd /c netsh wlan start hostednetwork"); 
p.waitFor(); 
BufferedReader reader=new BufferedReader(new InputStreamReader(p.getInputStream())); 
String line=reader.readLine(); 
while(line!=null) 
{ 
System.out.println(line);
        if(line.equalsIgnoreCase("The wireless local area network interface is powered down and doesn't support the requested operation.")==true)
        {
                  JOptionPane.showMessageDialog(null,"Sorry! Can not configure this interface. WiFi device is switched off. Check log for further clarification.");
                  create.setEnabled(true);
                  stop.setEnabled(false);
        
        }         
jTextArea1.append('\n'+line);
line=reader.readLine(); 
} 

} 
catch(IOException e1) {
    stop.setEnabled(false);
JOptionPane.showMessageDialog(null,"Sorry! Can not configure this interface");
} 
catch(InterruptedException e2) {
    stop.setEnabled(false);
JOptionPane.showMessageDialog(null,"Sorry! Can not configure this interface");
} 

 
 
 }   /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         //*///SU.run(new Form_Main(), args);
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                  // this.getContentPane().setBackground( Color.red );
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try{
                        Thread.sleep(0561);
                }
                catch(Exception e)
                {}
                //Form_Main.CENTER_ALIGNMENT;
                
                new Form_Main().setVisible(true);
                
               // Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
//Form_Main.class.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
             
                //stop.setEnabled(false);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton create;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JFrame jFailureFrame;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPsw;
    private javax.swing.JPasswordField jPsw1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JFrame jSuccessFrame;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jUsr;
    private javax.swing.JTextField jUsr1;
    private javax.swing.JButton stop;
    // End of variables declaration//GEN-END:variables
}
